### ISSUE TITLE
error

### ISSUE THREAD

**Issue by guillermooo** [fsharp/sublime-fsharp-package#75]
```
System.Exception was unhandled
  HResult=-2146233088
  Message=Exception when getting check options for 'C:\Users\Guillermo\Documents\Dev\Samples\fsharp-playground\foo.fsx'
.Details: System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Microsoft.FSharp.Control.AsyncBuilderImpl.commit[a](Result`1 res)
   at Microsoft.FSharp.Control.CancellationTokenOps.RunSynchronously[a](CancellationToken token, FSharpAsync`1 computation, FSharpOption`1 timeout)
   at Microsoft.FSharp.Control.FSharpAsync.RunSynchronously[T](FSharpAsync`1 computation, FSharpOption`1 timeout, FSharpOption`1 cancellationToken)
   at FSharp.CompilerBinding.LanguageService.GetScriptCheckerOptions(String fileName, String projFilename, String source)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

  Source=FSharp.Core
  StackTrace:
       at <StartupCode$FSharp-Core>.$Control.StartImmediate@1412-1.Invoke(Exception exn)
       at Microsoft.FSharp.Control.CancellationTokenOps.StartWithContinuations@1198-1.Invoke(Exception x)
       at Microsoft.FSharp.Control.Trampoline.ExecuteAction(FSharpFunc`2 firstAction)
       at Microsoft.FSharp.Control.AsyncBuilderImpl.startAsync[a](CancellationToken cancellationToken, FSharpFunc`2 cont, FSharpFunc`2 econt, FSharpFunc`2 ccont, FSharpAsync`1 p)
       at Microsoft.FSharp.Control.CancellationTokenOps.StartWithContinuations[T](CancellationToken token, FSharpAsync`1 a, FSharpFunc`2 cont, FSharpFunc`2 econt, FSharpFunc`2 ccont)
       at Microsoft.FSharp.Control.FSharpAsync.StartWithContinuations[T](FSharpAsync`1 computation, FSharpFunc`2 continuation, FSharpFunc`2 exceptionContinuation, FSharpFunc`2 cancellationContinuation, FSharpOption`1 cancellationToken)
       at Microsoft.FSharp.Control.FSharpAsync.StartImmediate(FSharpAsync`1 computation, FSharpOption`1 cancellationToken)
       at FSharp.InteractiveAutocomplete.Main.main(State state)
       at FSharp.InteractiveAutocomplete.Main.entry(String[] args)
  InnerException: 
```

**Comment by rojepp** [comment]
This problem is discussed [here](https://github.com/fsharp/FSharp.Compiler.Service/issues/337).

**Comment by rneatherway** [comment]
What versions of Visual Studio, if any, does this machine have installed?

**Comment by guillermooo** [comment]
VS 2012 Pro Update 4 IRRC.

**Comment by rneatherway** [comment]
Currently FSAC depends on MSBuild v12, which comes with VS2013. The discussions at https://github.com/fsharp/FSharp.Compiler.Service/pull/337 and https://github.com/fsharp/FSharp.Compiler.Service/pull/338 describe some of the issues trying to work around that. I don't know the best solution yet, sorry.
