### ISSUE TITLE
Sublime 4 - KeyError: 'on_modified_async'

### ISSUE THREAD

**Issue by JaggerJo** [fsharp/sublime-fsharp-package#92]
Just tried writing some F# in sublime 4. Autocomplete (Ctr + .) and other commands result in this error for me. The package was installed via. Package Control. 

I'm running on MacOS 11.2.3 (20D91) (intel)

```
reloading python 3.3 plugin Package Control.Package Control
reloading python 3.3 plugin FSharp.__init__
reloading python 3.3 plugin FSharp._init_
reloading python 3.3 plugin FSharp.execute
reloading python 3.3 plugin FSharp.fsharp
reloading python 3.3 plugin FSharp.xevents
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 310, in reload_plugin
    load_module(m)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 343, in load_module
    decorate_handler(t, method_name)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python33/sublime_plugin.py", line 226, in decorate_handler
    method = cls.__dict__[method_name]
KeyError: 'on_modified_async'
```

**Comment by adelarsq** [comment]
@JaggerJo Did you solve?
You can use https://github.com/sublimelsp/LSP with https://github.com/fsharp/FsAutoComplete

**Comment by ilog2000** [comment]
The same error for SublimeText 4 on Windows. I will try the packages @adelarsq recommends.
